### ISSUE TITLE
Installing npm and other stuff after with docker compose

### ISSUE THREAD

**Issue by Disane87** [cdr/code-server#1023]
I've encapsulated all the stuff for starting the code-server in a `docker-compose.yaml`but now I need to install some deps after the start, like nodejs, npm and angular-cli. How can I achieve this?

My `docker-compose.yaml`
```yml
version: "2"
services:
  code-server:
    image: codercom/code-server:v2
    container_name: code-server-v2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=${PWD}
    volumes:
      - ${HOME}/.local/share:/home/coder/.local/share
      - ${HOME}:/home/coder
    ports:
      - 8080:8080
      - 4200:4200
    restart: always
    command: "--auth password"

```

I've tried it with the `command` but I had no luck with it, chaining with the `--auth` flag
