### ISSUE TITLE
Multiline command in docker-compose not supported

### ISSUE THREAD

**Issue by SuperSandro2000** [cdr/code-server#1039]
- `code-server` --version
info  2.1568-vsc1.38.1
info  134040fea385c19cd00aa98b9b07c5d6a104fee8
info  x64

- OS Version: Docker version 19.03.3-beta1, build 7348bc0

## Description

When I start the container with
````
command:
  - --auth password
  - --disable-telemetry
````
in docker-compose I get the following
````
info  Server listening on http://0.0.0.0:8080
info    - No authentication
info    - Not serving HTTPS
````
Clearly code-server did not parse the args correctly.

## Steps to Reproduce

docker-compose.yml
````yaml
---
version: "2.4"
services:
  coder:
    image: codercom/code-server:v2
    security_opt:
      - seccomp:unconfined
    environment:
      - PASSWORD=123456
    command: --auth password --disable-telemetry
  coder-bug:
    image: codercom/code-server:v2
    security_opt:
      - seccomp:unconfined
    environment:
      - PASSWORD=123456
    command:
      - --auth password
      - --disable-telemetry
````
docker-compose run --rm coder
docker-compose run --rm coder-bug
