### ISSUE TITLE
Recommended way of adding access to /usr/bin/go / /usr/bin/dart etc in docker instance

### ISSUE THREAD

**Issue by agilob** [cdr/code-server#1124]
When running code-server I would like to install some plugins and support for code-runner and run code on the server. I have code-server running in docker using docker-compose:

```
version: "3.3"

services:
  vscode:
    container_name: vscode
    image: codercom/code-server:v2
    networks:
    volumes:
      - $HOME/dockers/vscode:/home/coder/.local/share/code-server
      - $HOME/dockers/vscode/project:/home/coder/project
    environment:
      - PASSWORD=xxxxx
    expose:
      - 8080
    restart: unless-stopped
```

I would like to add go and dart code runner support with dart/golang. What's your recommended way of fixing this issue:

```
[Running] dart "/main.dart"
/bin/sh: 1: dart: not found
```

which basically means, installing dart/go in docker or exposing `/usr/bin/` from host system?
