### ISSUE TITLE
code-server docker image problem with path in url

### ISSUE THREAD

**Issue by pwFoo** [cdr/code-server#1267]
I use a reverse proxy for ssl offloading and make code-server available with a sub path `https://example.com/vsc/` and map it to "/" of the container, but there are redirect problems. The sub path is removed from url during redirect to login for example.
```
  vscode:
    image: codercom/code-server
    labels:
      caddy.address: dev.example.com/vsc/
      caddy.targetport: '8080'
      caddy:targetpath: "/"
      caddy.proxy.websocket:
      caddy.proxy.transparent:
    networks:
      webproxy:
    stdin_open: true
    volumes:
    - project:/home/coder/project
    tty: true
    user: root
    command:
    - "--allow-http"
    - "--auth none"
```

If I add /vsc/ manually to the redirect url it works fine again. Redirect shouldn't. I also test theia ide without any problems by using a subpath ouside of the container mapped to container "/".
