### ISSUE TITLE
Fresh k8s install, "Internal server error", with no log output from Code-server

### ISSUE THREAD

**Issue by Richard87** [cdr/code-server#1377]
- `code-server` version: 
- OS Version: Microk8s/Fedora31 everything else works...

## Description
```
wget -O- https://code.r6.no
--2020-02-27 21:29:15--  https://code.r6.no/
Resolving code.r6.no (code.r6.no)... 92.221.87.36
Connecting to code.r6.no (code.r6.no)|92.221.87.36|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-02-27 21:29:15 ERROR 500: Internal Server Error.
```
## Steps to Reproduce

`kubectl apply -f `:
```yaml
apiVersion: v1
kind: Service
metadata:
 name: code-server
 namespace: code-server
spec:
 ports:
 - port: 8080
   name: https
   protocol: TCP
 selector:
   app: code-server
 type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
  name: code-server
  namespace: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - image: codercom/code-server:v2
        imagePullPolicy: Always
        name: code-server
        args:
        - --log=trace
        ports:
        - containerPort: 8080
          name: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: code-ingress
  namespace: code-server
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`code.r6.no`)
    kind: Rule
    services:
    - name: code-server
      port: 8080
  tls:
    certResolver: myresolver
```

Log output:
```
k -n code-server logs -f code-server-68c7c77684-mprjg
info  Server listening on http://0.0.0.0:8080
info    - Password is fancy-password
info      - To use your own password, set the PASSWORD environment variable
info      - To disable use `--auth none`
info    - Not serving HTTPS
```
Traefik logs:
```
10.1.69.1 - - [27/Feb/2020:20:14:36 +0000] "GET / HTTP/2.0" 500 21 "-" "-" 4216 "code-server-code-ingress-8124228899086cab3c34@kubernetescrd" "https://10.1.69.15:8080" 1ms
10.1.69.1 - - [27/Feb/2020:20:14:36 +0000] "GET /favicon.ico HTTP/2.0" 500 21 "-" "-" 4217 "code-server-code-ingress-8124228899086cab3c34@kubernetescrd" "https://10.1.69.15:8080" 1ms
10.1.69.1 - - [27/Feb/2020:20:15:27 +0000] "GET / HTTP/2.0" 500 21 "-" "-" 4240 "code-server-code-ingress-8124228899086cab3c34@kubernetescrd" "https://10.1.69.15:8080" 2ms
10.1.69.1 - - [27/Feb/2020:20:16:15 +0000] "GET / HTTP/2.0" 500 21 "-" "-" 4264 "code-server-code-ingress-8124228899086cab3c34@kubernetescrd" "https://10.1.69.15:8080" 1ms
10.1.69.1 - - [27/Feb/2020:20:16:53 +0000] "GET / HTTP/2.0" 500 21 "-" "-" 4283 "code-server-code-ingress-8124228899086cab3c34@kubernetescrd" "https://10.1.69.15:8080" 0ms
10.1.69.1 - - [27/Feb/2020:20:16:53 +0000] "GET /favicon.ico HTTP/2.0" 500 21 "-" "-" 4284 "code-server-code-ingress-8124228899086cab3c34@kubernetescrd" "https://10.1.69.15:8080" 0ms
10.1.69.1 - - [27/Feb/2020:20:16:58 +0000] "GET / HTTP/2.0" 500 21 "-" "-" 4288 "code-server-code-ingress-8124228899086cab3c34@kubernetescrd" "https://10.1.69.15:8080" 0ms
10.1.69.1 - - [27/Feb/2020:20:16:58 +0000] "GET /favicon.ico HTTP/2.0" 500 21 "-" "-" 4290 "code-server-code-ingress-8124228899086cab3c34@kubernetescrd" "https://10.1.69.15:8080" 2ms
10.1.69.1 - - [27/Feb/2020:20:26:02 +0000] "GET / HTTP/2.0" 500 21 "-" "-" 4572 "code-server-code-ingress-8124228899086cab3c34@kubernetescrd" "https://10.1.69.17:8080" 2ms
10.1.69.1 - - [27/Feb/2020:20:26:03 +0000] "GET /favicon.ico HTTP/2.0" 500 21 "-" "-" 4573 "code-server-code-ingress-8124228899086cab3c34@kubernetescrd" "https://10.1.69.17:8080" 2ms
10.1.69.1 - - [27/Feb/2020:20:26:32 +0000] "GET / HTTP/2.0" 500 21 "-" "-" 4595 "code-server-code-ingress-8124228899086cab3c34@kubernetescrd" "https://10.1.69.18:8080" 5ms
10.1.69.1 - - [27/Feb/2020:20:26:33 +0000] "GET /favicon.ico HTTP/2.0" 500 21 "-" "-" 4597 "code-server-code-ingress-8124228899086cab3c34@kubernetescrd" "https://10.1.69.18:8080" 0ms
10.1.69.1 - - [27/Feb/2020:20:26:49 +0000] "GET / HTTP/2.0" 500 21 "-" "-" 4606 "code-server-code-ingress-8124228899086cab3c34@kubernetescrd" "https://10.1.69.18:8080" 2ms
10.1.69.1 - - [27/Feb/2020:20:26:50 +0000] "GET /favicon.ico HTTP/2.0" 500 21 "-" "-" 4608 "code-server-code-ingress-8124228899086cab3c34@kubernetescrd" "https://10.1.69.18:8080" 0ms
10.1.69.1 - - [27/Feb/2020:20:29:15 +0000] "GET / HTTP/1.1" 500 21 "-" "-" 4675 "code-server-code-ingress-8124228899086cab3c34@kubernetescrd" "https://10.1.69.18:8080" 0ms
```
