### ISSUE TITLE
Unable to use allow-http-, auth: none

### ISSUE THREAD

**Issue by mahmoudajawad** [cdr/code-server#1428]
Although I found few references to using `--allow-http`, and `--auth none` in few issues, I still wasn't able to use them myself. My docker-compose file is:
```
version: '3.3'

services:
  code-server:
    image: code-server-hw
    volumes:
      - ./project:/home/coder/project
    ports:
      - "48080:8080"
    command:
      - "--allow-http"
      - "--auth none"
```
The results are:
```
code-server_1  | Option 'allow-http' is unknown. Ignoring.
code-server_1  | Option 'auth none' is unknown. Ignoring.
code-server_1  | Option 'allow-http' is unknown. Ignoring.
code-server_1  | Option 'auth none' is unknown. Ignoring.
code-server_1  | info  Server listening on http://0.0.0.0:8080
code-server_1  | info    - Password is 44a2da8ed099563b9d903813
code-server_1  | info      - To use your own password, set the PASSWORD environment variable
code-server_1  | info      - To disable use `--auth none`
code-server_1  | info    - Not serving HTTPS
```

version info:
```
Version: 1.41.1
Commit: f51e045cd5483561afc07694f39307fb673b6d1d
Date: 2020-01-17T22:58:55.612Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36 Edg/80.0.361.66
Code Server Version: 2.1698-vsc1.41.1
```
