### ISSUE TITLE
Can't use when I set sub url reverse-proxy 

### ISSUE THREAD

**Issue by deadcatssociety** [cdr/code-server#1608]
Hello, First, sorry for my english skill.

I use [Traefik](https://containo.us/traefik/) for reverse proxy.
I want to use code-server domain like `https://<mydomain>/vscode` <-> docker code-server

but when I set subdomain to code-server, always show me error page by traefik (401 error)
I think it occured by redirecting to login page

 When I test same option and change code-server running into root domain(`https://<mydomain>`), It works, but when I use subdomain(`https://<mydomain>/vscode`), It broken.

My code server version is 3.2.0 + linux-server's docker image

I don't know it is traefik setting issue or code-server issue exactly.
Please help

my docker swarm compose file is:
```yml
version: "3.3"
services:
  vscode:
    image: linuxserver/code-server:latest
    environment:
      - PUID=1004
      - PGID=1004
      - TZ=Asia/Seoul
      - PASSWORD=<PASSWORD>
      - SUDO_PASSWORD=<PASSWORD>
    volumes:
      - /home/swarm/vscode/config:/home/coder/.local/share/code-server
      - /home/swarm/vscode/workspace:/home/coder/project
    networks:
      - traefik
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == <INSTANCE NAME>
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vscode.rule=Host(`<DOMAIN NAME>`) && PathPrefix(`/vscode`)"
        - "traefik.http.routers.vscode.entrypoints=websecure"
        - "traefik.http.services.vscode.loadbalancer.server.port=8443"

networks:
  traefik:
    external: true
```
