### ISSUE TITLE
Most stable server OS for running code-server in a vps?

### ISSUE THREAD

**Issue by zk-g** [cdr/code-server#169]
And how to keep it working in background,
it have problem with screen #67   and I haven't try in others way yet.
Running in Debian without screen return the error  #121 even if the server keep working.
In general I also notice a global slowdowns in loading files and folders.

**Comment by NGTmeaty** [comment]
I believe we are recommending Ubuntu 16.04 at the moment.

**Comment by mko-x** [comment]
I run pretty stable with this configuration:

```yaml
version: '3.7'
services:
    nginx-proxy:
        #image: jwilder/nginx-proxy:alpine replaced by extended Dockerfile
        build: .
        container_name: proxy
        image: mkox/nginx-proxy
        ports:
        - "80:80" #http redirect
        - "443:443" #https
        volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro # listening to docker events
        - /etc/certs:/etc/nginx/certs # host place for ssl certs
        environment:
            DEFAULT_HOST: domain.tld
        networks:
            - outpost_network

    codeserver:
        image: codercom/code-server
        container_name: code
        volumes:
            # for scaling (swarm/stack) instances can share same workspace
            # depending on fs type/emu
            - /opt/docker/codeserver/projects:/opt/projects
            - /opt/docker/codeserver/data:/data
        environment:
            # nginx-proxy will autodetect
            VIRTUAL_HOST: code.domain.tld
            # code-server defaults to 8443
            VIRTUAL_PORT: 8443
        # start code-server
        # https is handled by proxy so http is ok 
        # set a pw (!)
        # ARG: desired project workspace
        command: code-server --allow-http --password=code-server-rocks /opt/projects
        # code-server --help
        # ARGUMENTS
        #     WORKDIR  [default: (directory to binary)] Specify working dir

        # OPTIONS
        #     -d, --data-dir=data-dir
        #     -h, --host=host          [default: 0.0.0.0]
        #     -o, --open               Open in browser on startup
        #     -p, --port=port          [default: 8443] Port to bind on
        #     -v, --version            show CLI version
        #     --allow-http
        #     --cert=cert
        #     --cert-key=cert-key
        #     --help                   show CLI help
        #     --no-auth
        #     --password=password
        networks:
            outpost_network:

networks:
    outpost_network:
      driver: bridge
      name: outpost_network
```

My custom nginx-proxy Dockerfile

```dockerfile
FROM jwilder/nginx-proxy:alpine
LABEL maintainer="m-ko"
RUN apk add --no-cache nano logrotate
COPY ./nginxlog.conf /etc/logrotate.d/nginx
RUN { \
      echo 'server_tokens off;'; \
      echo 'client_max_body_size 200m;'; \
    } > /etc/nginx/conf.d/override_proxy.conf

```
