### ISSUE TITLE
Serve helm chart more idiomatically

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#2302]
See https://github.com/cdr/code-server/pull/2048#issuecomment-724951228

**Comment by nhooyr** [comment]
Instead of GH pages, we can push to https://artifacthub.io

**Comment by Matthew-Beckett** [comment]
@nhooyr is this to be picked up internally due to the dependence on ArtifactHub or are you looking for people to contribute to the CI/GitHub Actions element?

**Comment by nhooyr** [comment]
So re artifact hub looks like I was wrong, we still need to host our own helm repository.

I think this is best handled internally. I'll try to get this done for the next release.

**Comment by jgillich** [comment]
You can use [GitHub actions](https://github.com/marketplace/actions/helm-chart-releaser) to build the chart automatically and host it on this repo's gh-pages branch, there is no need for another service. It's super simple, [here](https://github.com/fluxcd-community/helm-charts) is a sample repo that uses this setup.

Let me know if I can help.

**Comment by jsjoeio** [comment]
Oh wow, good to know! Thanks for the links and offering to help. When we tackle this, we may add you as a PR reviewer if that's okay

**Comment by geraldwuhoo** [comment]
Any updates on this? Not sure if [this chart]{https://artifacthub.io/packages/helm/deploy-code-server/code-server} is official or not, but it is quite out of date when compared to the Chart version in this git repo (1.0.3 vs 2.0.1 for Chart, 3.10.2 vs 4.0.2 for Application). Having a "real" Helm repository to refer to would make gitops deployments much easier.

**Comment by anthosz** [comment]
Hello,

Do we have any news on that issue?

**Comment by code-asher** [comment]
No plans on changing anything with the Helm chart at the moment.

**Comment by egvimo** [comment]
**Proposal**: Publish the Helm chart to an OCI registry (e.g., GitHub Container Registry) to enable direct installation.

#### Example pipeline

```yaml
name: Publish Helm Chart

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Package and Push Chart
        run: |
          helm package ./ci/helm-chart
          helm push code-server-*.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
```
