### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by korzq** [cdr/code-server#261]
ipv4 is going to die. Let's support ipv6

**Comment by pokemonlover1234** [comment]
I'd say support ipv6 even if ipv4 doesnt die

**Comment by nol166** [comment]
I agree this would be pretty neat

**Comment by delfer** [comment]
IPv6 works.
Just start server with arguments like `./code-server -h :: -p 8080 -H -P password`
Where is `::` is like `0.0.0.0` but for IPv6.
Now you can open Code-server in Chrome by IPv6 address like `http://[2022:1111:1111:1111:1111:1111:1111:1111]:8080/` (Change it to your IPv6).
With other browsers (Firefox and Edge) here is small bug https://github.com/cdr/code-server/issues/739
But I fond workaround: just add DNS AAAA record and it will work with any browser.
Personally I use https://www.dynu.com/ and set IP with cron job:
```
# m h  dom mon dow   command
  * *    *   *   *   /usr/bin/curl 'https://api.dynu.com/nic/update?hostname=MY.DOMAN.NAME&alias=ALIAS&myip=no&myipv6=yes&password=MYDYNUPASSWORD'
```

**Comment by cxh1205** [comment]
IPv6 and IPv4 both work.

Modify the file ~/.config/code-server/config.yaml:

```yaml
bind-addr: "[::]:8080"
auth: password
password: your password
cert: false
```

Then you can enjoy accessing `http://ipv4-address:8080/` and `http://[ipv6-address]:8080/` in your browser.

IPv6和IPv4都可以正常工作。

修改~/.config/code-server/config.yaml文件：

```yaml
bind-addr: "[::]:8080"
auth: password
password: your password
cert: false
```

然后在浏览器中输入`http://ipv4-address:8080/`和`http://[ipv6-address]:8080/`即可访问。
