### ISSUE TITLE
Create extension/config to initialize code-server

### ISSUE THREAD

**Issue by arita37** [cdr/code-server#2831]
We want to initialize code-server with some-preset 
save into a yaml file on disk.

**Comment by jsjoeio** [comment]
Hi @arita37 - this is already possible, to some extent. If you look at the logs when code-server starts, it uses a config file somewhere on your machine like: `~/.config/code-server/config.yaml`

<img width="931" alt="image" src="https://user-images.githubusercontent.com/3806031/110355982-04da5800-7ff7-11eb-8a50-453e275e7108.png">

Here's what the file looks like:

```yaml
bind-addr: 127.0.0.1:8080
auth: password
password: helloworld
cert: false
```

Any flag that the CLI accepts should be configurable in the yaml file. Hope that helps! Please reopen if I misunderstood and you need something else!
