### ISSUE TITLE
Blank Page after Login with HTTPS

### ISSUE THREAD

**Issue by Eternity714** [cdr/code-server#3017]
## OS/Web Information

- Web Browser: Chrome
- Local OS: Win10 x64
- Remote OS: docker
- `code-server --version`: latest

## Expected

When I use https, it can be login, after that, it becomes to a blank page

## Actual

i have not idea

## Config File

docker-compose.yml
```
version: "3.8"
services:
  frpc:
    image: snowdreamtech/frpc
    volumes:
      - "./frpc.ini:/etc/frp/frpc.ini:ro"
      - "./code.gkotta.cn.crt:/etc/frp/server.crt:ro"
      - "./code.gkotta.cn.key:/etc/frp/server.key:ro"
    restart: unless-stopped
    networks:
      backend:
    environment:
      - "LOCAL_ADDR=code"
      - "LOCAL_PORT=8080"
      - "SUBDOMAIN=code"
  code-server:
    image: codercom/code-server
    ports:
      - "8080:8080"
    volumes:
      - "./data:/home/coder/project"
    environment:
      - "PASSWORD=******"
    restart: unless-stopped
    networks:
      backend:
        aliases:
          - code

networks:
  backend:
```

frpc.ini
```
[common]
server_addr = x.x.x.x
server_port = 7000

[code-server]
type = http
local_ip = code
local_port = 8080
subdomain = code

[code-server-https]
type = https
subdomain = code

plugin = https2http
plugin_local_addr = code:8080

# HTTPS 证书相关的配置
plugin_crt_path = /etc/frp/server.crt
plugin_key_path = /etc/frp/server.key
plugin_host_header_rewrite = 127.0.0.1
plugin_header_X-From-Where = frp
```

## Note
In addition，i can't find any way to cache the log file
