### ISSUE TITLE
Add stale bot

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#4016]
Add stale bot (suggested by @jawnsy) to auto-clean-up old issues older than 180 days. We should use `exemptLabels` too.

```yml
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 14
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 5
# Label to apply when stale.
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no activity occurs in the next 5 days.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
```
