### ISSUE TITLE
Docker persistency

### ISSUE THREAD

**Issue by omniait** [cdr/code-server#505]
## Description

Hello, I'm currently using the docker image of code-server, but I have a problem regarding persistency: if I restart the container the extensions are gone, I don't want to keep the container running because otherwise I could not upgrade it and the server could be restarted for a number of reasons; I know that I should mount a volume but what folders should I sync to the host? In the same philosophy how could I also save the git config with the private keys for my repositories?
Thanks

**Comment by romanrehacek** [comment]
@omniait Hi, you can try my [docker file](https://github.com/romanrehacek/vscode-ide). I install extensions in build proccess, so extensions are in docker image.
First, you need to install "Sync settings" extension in current vscode and save settings into github gist.
Than modify sync.gist file with your gist id and build Dockefile. After than, you run your image and you should have vscode with your extensions and settings.

**Comment by RyanEwen** [comment]
You should only need to create a volume to persist /root/.local/share/code-server

```
version: '2.2'

services:
  vscode:
    image: codercom/code-server
    volumes:
      - ./:/root/project
      - data:/root/.local/share/code-server
    network_mode: "host"
    restart: always
    command: [ --allow-http, --password=whatever ]

volumes:
  data:
```
