### ISSUE TITLE
Can't save or edit existing code. Is there a safe way to edit/get ownership or inherited permission of existing code from persistent volume of host when running code-server in Docker?

### ISSUE THREAD

**Issue by MostHated** [cdr/code-server#631]
## Description
Hello all,  
I am running code-server using Docker-Compose with mapped persistent volumes for th eproject folder as well as the data/extensions as seen below to a folder in which I have many repos on the host server in hopes to be able to edit the code on the go, but when I try to edit it, I get permission issues when trying to save, it asks if I would like to try using sudo, but that fails as well. 

I am able to create folder through the code-server terminal using sudo, but that seems about all. Do I have to make some sort of permission change outside of the container first so that when code-server is running and it mounts the persistent volume of the host that I can edit/save/create more easily? 

Here is how my Docker-Compose is setup:

```yaml

version: '2.2'

services:
  vscode:
    image: codercom/code-server:latest
    container_name: vscode
    environment:
      - PASSWORD=mypass
    volumes:
      - code_repos:/home/coder/project
      - vscode_data:/root/.local/share/code-server
    restart: always
    command: --allow-http  -p 4572
    network_mode: "host"

volumes:
  code_repos:
    driver: local
    driver_opts:
      o: bind
      device: /home/user/devtools/repos  
  vscode_data:
    driver: local
    driver_opts:
      o: bind
      device: /mnt/disks/data_store/vscode_data

```

Thanks!
-MH
