### ISSUE TITLE
nginx reverse proxy opens "coder" user home directory instead of project directory

### ISSUE THREAD

**Issue by mandiwise** [cdr/code-server#644]
## Description

When I run code-server by itself everything launches as expected, but when I add an nginx reverse proxy something strange happens. 

Rather than opening the project dir when I navigate to my URL to launch code-server, it launches one level up in the home directory for the `coder` user instead (so I see the project dir in there as a sub-directory, along with a number of hidden files and folders too). Not sure if I've configured something incorrectly?

This is is what I'm working with:

`docker-compose.yml`:

```
version: "3"

services:
  codeserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_EMAIL: ${GIT_EMAIL}
        GIT_NAME: ${GIT_NAME}
    image: codercom/code-server:latest
    container_name: codeserver
    restart: always
    volumes:
      - ${PROJECT_DIR}:/home/coder/project
volumes:
  codeserver:
    driver: local
```

`docker-compose.prod.yml`:

```
version: "3"

services:
  codeserver:
    environment:
      PASSWORD: ${PASSWORD}
      DOMAIN: ${DOMAIN}
    expose:
      - 8443
    command: --allow-http
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    environment:
      DOMAIN: ${DOMAIN}
    command: >
      /bin/sh -c 'envsubst "$$DOMAIN" < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && 
      nginx -g "daemon off;"'
    depends_on:
      - codeserver
```

`nginx.template`:

```
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    location / {
       proxy_pass   http://codeserver:8443;
       proxy_set_header     Upgrade         $http_upgrade;
       proxy_set_header     Connection      upgrade;
       proxy_set_header     Accept-Encoding gzip;
    }
}
```

I'm not an nginx expert, so any insight would be appreciated!
