### ISSUE TITLE
No permissions over home directory (error EACCES: permission denied, mkdir '/home/coder/.config/code-server')

### ISSUE THREAD

**Issue by javierspn** [cdr/code-server#7353]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox, Chrome, Edge
- Local OS: Debian 12, MacOS X Ventura, Windows 11, Windows 10
- Remote OS: Debian 12
- Remote Architecture: x86 (64 bits)
- `code-server --version`: latest

### Steps to Reproduce

1. Run docker stack
2. Wait to be up
3. Doesn't startup (see logs below)

### Expected

For the container to start up

### Actual

It doesn't start

### Logs

```shell
code-server  | [2025-05-16T11:04:28.013Z] error EACCES: permission denied, mkdir '/home/coder/.config/code-server'
code-server  | [2025-05-16T11:04:28.575Z] error EACCES: permission denied, mkdir '/home/coder/.config/code-server'
code-server  | [2025-05-16T11:04:29.179Z] error EACCES: permission denied, mkdir '/home/coder/.config/code-server'
code-server  | [2025-05-16T11:04:29.975Z] error EACCES: permission denied, mkdir '/home/coder/.config/code-server'
code-server  | [2025-05-16T11:04:31.160Z] error EACCES: permission denied, mkdir '/home/coder/.config/code-server'
code-server  | [2025-05-16T11:04:33.132Z] error EACCES: permission denied, mkdir '/home/coder/.config/code-server'
code-server  | [2025-05-16T11:04:36.745Z] error EACCES: permission denied, mkdir '/home/coder/.config/code-server'
code-server  | [2025-05-16T11:04:43.535Z] error EACCES: permission denied, mkdir '/home/coder/.config/code-server'
code-server  | [2025-05-16T11:04:56.756Z] error EACCES: permission denied, mkdir '/home/coder/.config/code-server'
code-server  | [2025-05-16T11:05:22.764Z] error EACCES: permission denied, mkdir '/home/coder/.config/code-server'
code-server  | [2025-05-16T11:06:14.407Z] error EACCES: permission denied, mkdir '/home/coder/.config/code-server'
code-server  | [2025-05-16T11:07:14.828Z] error EACCES: permission denied, mkdir '/home/coder/.config/code-server'
code-server  | [2025-05-16T11:08:15.240Z] error EACCES: permission denied, mkdir '/home/coder/.config/code-server'
```

### Does this bug reproduce in native VS Code?

I did not test native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [x] I am using a secure context.

### Notes

I am trying to run a container (docker compose stack) and it is not working because of a permissions issue. My stack's config:

```yaml
x-common-logging: &default-logging
  driver: ${LOG_TYPE}
  options:
    max-size: ${LOG_SIZE}
    max-file: ${LOG_FILES}


services:

  code-server:

    image: ${CONTAINER_IMAGE}
    container_name: ${CONTAINER_NAME}

    restart: ${POLICY_RESTART}

    environment:

      TZ: ${TZ}
      PUID: 0
      PGID: 0
      DOCKER_USER: 0

    networks:
      - proxied

    volumes:
      - ${CODE_LOCAL_VOLUME}
      - ${CODE_CONFIG_VOLUME}
      - ${CODE_PROJECT_VOLUME}

    logging: *default-logging


networks:
  proxied:
    name: proxied
```

```shell
CONTAINER_IMAGE=codercom/code-server:latest
CONTAINER_NAME=code-server
# VOLUMES
CODE_LOCAL_VOLUME=/docker/data/code/.local:/home/coder/.local
CODE_CONFIG_VOLUME=/docker/data/code/.config:/home/coder/.config
CODE_PROJECT_VOLUME=/docker/data/code/projects:/home/coder/project
# COMMON ENVIRONMENT VARIABLES
TZ=Europe/Madrid
POLICY_RESTART=unless-stopped
LOG_TYPE=json-file
LOG_SIZE=10M
LOG_FILES=3
```

I have changed the DOCKER_USER to the actual docker user and the root, none of them work.
