### ISSUE TITLE
Extra brackets automatically added during AI autocompletion with Continue.dev extension

### ISSUE THREAD

**Issue by exetroncorp** [cdr/code-server#7397]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

-  Web Browser: Chrome
-  Remote OS: Debain 12
- `code-server --version`: 1.101.2

## Step 1: Install Continue.dev

Install the Continue.dev extension in your IDE.

## Step 2: Configure Continue with Codestral Free API

Configure Continue to use the Codestral free API key for autocomplete functionality.

### Example Configuration

```yaml
name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: Codestral
    provider: mistral
    model: codestral-latest
    apiKey: XXXXXXXXXXXXXXXXXXXXXXXXXX
    roles:
      - autocomplete
      - chat
      - edit
      - apply
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
```

## Step 3: Enable Auto-complete

Enable the auto-complete feature in Continue.dev settings.

## Step 4: Create Test File

Create a new file named `Robertor.java` and add the following comment:

```java
// a java swing programm that takes an input X number and display a circle with the radius of X
```

## Step 5: Test Autocomplete

1. Move to the next line by pressing **Enter**
2. Accept suggestions using the **Tab** key

## Issue: Extra Bracket Appears

An extra bracket appears during autocomplete, as demonstrated in the capture video.

https://github.com/user-attachments/assets/2f9fb6a3-a250-493b-a956-b6383cf01217

### Expected

No extra bracket like in openvscode-server or codespaces :

https://github.com/user-attachments/assets/8e67a3b5-118f-4f26-81d8-d0e11c4f486b

### Actual

I dont know but code completion appearing in continue console doesnt'have bracket .
That means that the issue is during insertion in the ghost view text , something is auto adding brackets. 

### Logs

```shell

```

### Screenshot/Video

On code-server , extra bracket :

https://github.com/user-attachments/assets/2f9fb6a3-a250-493b-a956-b6383cf01217

Working example on codespace :

https://github.com/user-attachments/assets/aadf4d89-d307-4e96-b304-ed4461a8c5d2

### Does this bug reproduce in native VS Code?

No, this works as expected in native VS Code

### Does this bug reproduce in GitHub Codespaces?

No, this works as expected in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [x] I am using a secure context.
