### ISSUE TITLE
Unable to download any extensions/language support. 

### ISSUE THREAD

**Issue by leveled** [cdr/code-server#815]
- `code-server` version: 1.1156(?) - Latest version from dockerhub (https://hub.docker.com/r/codercom/code-server)
- OS Version: Ubuntu 18.04.2 LTS 

## Description

I'm unable to install any of the listed extensions on the Welcome page (or reach the store), including Vim bindings, language support, etc.) On the README it's noted that extensions are available through the custom store, although no instructions are provided on how to connect to it. 

## Steps to Reproduce

Docker Compose File 
```
services:
    code-server:
        container_name: code-server
        image: codercom/code-server
        restart: always
        volumes:
          - ${PWD}/projects:/home/coder/project
        environment:
          PASSWORD: xxx
        networks:
          - xxx
        command: --allow-http --disable-telemetry
        labels:
          - "traefik.enable=true"
          - "traefik.frontend.rule=Host:vscode.xxx"
          - "traefik.port=8443"
          - "traefik.docker.network=xxx"

networks:
    xxx:
        external: true
```
