### ISSUE TITLE
Permission issue, cannot start container

### ISSUE THREAD

**Issue by mkono87** [cdr/code-server#910]
## Description
Used the example to create a docker-compose but im getting permisson errors and the container wont start.
```
  vscode:
    image: codercom/code-server
    container_name: vscode
    ports:
      - 8443:8443
    volumes:
      - /srv/docker/:/home/coder/project
    command: code-server --no-auth --disable-telemetry
```

```
ERROR { [Error: EACCES: permission denied, mkdir '/home/coder/project/code-server']


  [stack]:


   'Error: EACCES: permission denied, mkdir \'/home/coder/project/code-server\'',


  [message]:


   'EACCES: permission denied, mkdir \'/home/coder/project/code-server\'',


  errno: -13,


  code: 'EACCES',


  syscall: 'mkdir',


  path: '/home/coder/project/code-server' }
```
