### ISSUE TITLE
I can't install extension by --install-extension

### ISSUE THREAD

**Issue by leeli73** [cdr/code-server#926]
I try to move code-server to /usr/bin , when I install extension by --install-extension,the output show extension install success,but I can't find it in extension list of code-server,and extension is not activited.PS:I changed the data-dir and extension-dir.

**Comment by Vorob-Astronaut** [comment]
the same for me

**Comment by Vorob-Astronaut** [comment]
my docker-compose file

```
  ide:
    image: registry.gitlab.com/demodesk/vscode
    container_name: deaddesk-ide
    hostname: demodesk-ide
    command: --allow-http --disable-telemetry --password 'HuL1PALIsH'
    user: 0:0
    volumes:
      - ./:/home/coder/deaddesk
      - /root/.gitconfig:/root/.gitconfig
      - /root/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      development:
```
