### ISSUE TITLE
How to expose the server at a subpath behind Kubernetes ingress in version 2

### ISSUE THREAD

**Issue by yuha0** [cdr/code-server#975]
## Description

I am running the code server version 2 (docker image: `codercom/code-server:2.1472-vsc1.38.1`) in Kubernetes and need to access it at https://example.com/code, which is controlled by an Ingress Controller. I notice that there's a `--base-path` option in the command line argument but it is not working for me.

The Kubernetes manifest:

```
apiVersion: v1
kind: Service
metadata:
  name: code-server
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
  selector:
    app: code-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
  name: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - image: codercom/code-server:2.1472-vsc1.38.1
        name: code-servery
        args:
        - --no-auth
        - --disable-telemetry
        - --allow-http
        - --log debug
        - --base-path https://example.com/code
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: code-server
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  tls:
  - hosts:
    - example.com
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: code-server
          servicePort: 8080
        path: /code(/|$)(.*)
```

## Related Issues
https://github.com/cdr/code-server/issues/241
